# docker-compose.yml
version: '3.8'
services:
  web:
    build: .
    container_name: login_web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql:8.0
    container_name: login_db
    environment:
      MYSQL_ROOT_PASSWORD: admin123 # ¡Importante!
      MYSQL_DATABASE: ProyectoFinalCS
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: login_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "8081:80"

volumes:
  db_data: